"""
Error Locator Agent

This module identifies specific code fragments (with line numbers) where errors occur
based on corrections generated by the Code Corrector Agent.
"""

from src.agents.error_locator.error_locator import ErrorLocatorAgent

__all__ = ["ErrorLocatorAgent"]
